/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R112RouteImport } from './routes/112'
import { Route as R168RouteImport } from './routes/168'
import { Route as R256RouteImport } from './routes/256'
import { Route as ActualWorkRouteImport } from './routes/actual-work'
import { Route as HatsRouteImport } from './routes/hats'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PrintedCamoRouteImport } from './routes/printed-camo'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R112Route = R112RouteImport.update({
  id: '/112',
  path: '/112',
  getParentRoute: () => rootRouteImport,
} as any)
const R168Route = R168RouteImport.update({
  id: '/168',
  path: '/168',
  getParentRoute: () => rootRouteImport,
} as any)
const R256Route = R256RouteImport.update({
  id: '/256',
  path: '/256',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualWorkRoute = ActualWorkRouteImport.update({
  id: '/actual-work',
  path: '/actual-work',
  getParentRoute: () => rootRouteImport,
} as any)
const HatsRoute = HatsRouteImport.update({
  id: '/hats',
  path: '/hats',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintedCamoRoute = PrintedCamoRouteImport.update({
  id: '/printed-camo',
  path: '/printed-camo',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/112': typeof R112Route
  '/168': typeof R168Route
  '/256': typeof R256Route
  '/actual-work': typeof ActualWorkRoute
  '/hats': typeof HatsRoute
  '/order': typeof OrderRoute
  '/printed-camo': typeof PrintedCamoRoute
  '/studio': typeof StudioRoute
  '/api/checkout': typeof ApiCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/112': typeof R112Route
  '/168': typeof R168Route
  '/256': typeof R256Route
  '/actual-work': typeof ActualWorkRoute
  '/hats': typeof HatsRoute
  '/order': typeof OrderRoute
  '/printed-camo': typeof PrintedCamoRoute
  '/studio': typeof StudioRoute
  '/api/checkout': typeof ApiCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/112': typeof R112Route
  '/168': typeof R168Route
  '/256': typeof R256Route
  '/actual-work': typeof ActualWorkRoute
  '/hats': typeof HatsRoute
  '/order': typeof OrderRoute
  '/printed-camo': typeof PrintedCamoRoute
  '/studio': typeof StudioRoute
  '/api/checkout': typeof ApiCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/112'
    | '/168'
    | '/256'
    | '/actual-work'
    | '/hats'
    | '/order'
    | '/printed-camo'
    | '/studio'
    | '/api/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/112'
    | '/168'
    | '/256'
    | '/actual-work'
    | '/hats'
    | '/order'
    | '/printed-camo'
    | '/studio'
    | '/api/checkout'
  id:
    | '__root__'
    | '/'
    | '/112'
    | '/168'
    | '/256'
    | '/actual-work'
    | '/hats'
    | '/order'
    | '/printed-camo'
    | '/studio'
    | '/api/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R112Route: typeof R112Route
  R168Route: typeof R168Route
  R256Route: typeof R256Route
  ActualWorkRoute: typeof ActualWorkRoute
  HatsRoute: typeof HatsRoute
  OrderRoute: typeof OrderRoute
  PrintedCamoRoute: typeof PrintedCamoRoute
  StudioRoute: typeof StudioRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/112': {
      id: '/112'
      path: '/112'
      fullPath: '/112'
      preLoaderRoute: typeof R112RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/168': {
      id: '/168'
      path: '/168'
      fullPath: '/168'
      preLoaderRoute: typeof R168RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/256': {
      id: '/256'
      path: '/256'
      fullPath: '/256'
      preLoaderRoute: typeof R256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actual-work': {
      id: '/actual-work'
      path: '/actual-work'
      fullPath: '/actual-work'
      preLoaderRoute: typeof ActualWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hats': {
      id: '/hats'
      path: '/hats'
      fullPath: '/hats'
      preLoaderRoute: typeof HatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printed-camo': {
      id: '/printed-camo'
      path: '/printed-camo'
      fullPath: '/printed-camo'
      preLoaderRoute: typeof PrintedCamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R112Route: R112Route,
  R168Route: R168Route,
  R256Route: R256Route,
  ActualWorkRoute: ActualWorkRoute,
  HatsRoute: HatsRoute,
  OrderRoute: OrderRoute,
  PrintedCamoRoute: PrintedCamoRoute,
  StudioRoute: StudioRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
